version: '3'

services:
    wordpress:
      image: wordpress
      environment:
          WORDPRESS_DB_HOST: 'db'
          WORDPRESS_DB_USER: 'wpuser'
          WORDPRESS_DB_PASSWORD: 'wppassword'
          WORDPRESS_DB_NAME: wpdb
          WORDPRESS_TABLE_PREFIX: 'wp_'
          WORDPRESS_DEBUG: '1'
      ports:
        - 80:80
      volumes:
        - wordpress:/var/www/html
      depends_on:
        - db
    db:
      image: mysql
      environment:
        MYSQL_DATABASE: wpdb
        MYSQL_USER: wpuser
        MYSQL_PASSWORD: wppassword
        MYSQL_RANDOM_ROOT_PASSWORD: '1'
      volumes:
        - db:/var/lib/mysql
    
volumes:
  wordpress:
  db:
